server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meblog_db_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.lzw.meblog.model

#showSql
logging:
  level:
    com:
      lzw:
        meblog:
          mapper : debug